# pyproject.toml
[tool.ruff]
[tool.eslint]
extends = "eslint:recommended"
env = { es6 = true, browser = true }
parserOptions = { ecmaVersion = 2018, sourceType = "module" }
globals = { Atomics = "readonly", SharedArrayBuffer = "readonly" }

[tool.eslint.rules]
indent = ["error", 2]
linebreak-style = ["error", "unix"]
quotes = ["error", "double"]
semi = ["error", "always"]

lint.ignore = ["E701"]
